[package]
org = "ballerinax"
name = "np"
version = "0.9.0"
authors = ["Ballerina"]
keywords = ["natural programming", "ai"]
repository = "https://github.com/ballerina-platform/module-ballerinax-np"
license = ["Apache-2.0"]
distribution = "2201.11.0"

[[package.modules]]
name = "np.openai"
export = true

[[package.modules]]
name = "np.azure.openai"
export = true

[platform.java21]
graalvmCompatible = true

[build-options]
observabilityIncluded = true

[[platform.java21.dependency]]
groupId = "io.ballerina.libx"
artifactId = "np-native"
version = "0.9.0"
path = "../native/build/libs/np-native-0.9.0-SNAPSHOT.jar"
